name: Profile summary cards

on:
  workflow_dispatch:
  schedule:
    - cron: "17 18 * * *"
  push:
    branches:
      - main
    paths:
      - "README.md"
      - ".github/workflows/profile-summary-cards.yml"
      - "assets/**"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - uses: vn7n24fzkq/github-profile-summary-cards@release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          USERNAME: ${{ github.repository_owner }}
          BRANCH_NAME: main
          UTC_OFFSET: 8
          EXCLUDE: ""
          AUTO_PUSH: true
